// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gp8HPpI_ZmmGlLU-5XWdNpk3xU5LH48',
    appId: '1:481215011720:web:33e24f18299d232944b83d',
    messagingSenderId: '481215011720',
    projectId: 'chitragame-79d67',
    authDomain: 'chitragame-79d67.firebaseapp.com',
    storageBucket: 'chitragame-79d67.firebasestorage.app',
    measurementId: 'G-8E39E8CPVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8j5yPL1GsJVgpG5mvZe-s7P14IYEjsE',
    appId: '1:481215011720:android:a319ad2be9514a7044b83d',
    messagingSenderId: '481215011720',
    projectId: 'chitragame-79d67',
    storageBucket: 'chitragame-79d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwSPVBJ8rPvduXhTymwv34RBVjMlXX2Eo',
    appId: '1:481215011720:ios:0963836b8ef8272944b83d',
    messagingSenderId: '481215011720',
    projectId: 'chitragame-79d67',
    storageBucket: 'chitragame-79d67.firebasestorage.app',
    iosClientId: '481215011720-u5lbdai84l6mdejhj2937unmar0gd3o6.apps.googleusercontent.com',
    iosBundleId: 'com.shalin.chitragame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwSPVBJ8rPvduXhTymwv34RBVjMlXX2Eo',
    appId: '1:481215011720:ios:0963836b8ef8272944b83d',
    messagingSenderId: '481215011720',
    projectId: 'chitragame-79d67',
    storageBucket: 'chitragame-79d67.firebasestorage.app',
    iosClientId: '481215011720-u5lbdai84l6mdejhj2937unmar0gd3o6.apps.googleusercontent.com',
    iosBundleId: 'com.shalin.chitragame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3gp8HPpI_ZmmGlLU-5XWdNpk3xU5LH48',
    appId: '1:481215011720:web:38dc8f748091274344b83d',
    messagingSenderId: '481215011720',
    projectId: 'chitragame-79d67',
    authDomain: 'chitragame-79d67.firebaseapp.com',
    storageBucket: 'chitragame-79d67.firebasestorage.app',
    measurementId: 'G-Y7DG81F0E7',
  );

}