// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: invalid_use_of_internal_member, deprecated_member_use_from_same_package, deprecated_member_use

part of 'app_router.dart';
 
// **************************************************************************
// RiverpodGenerator
// **************************************************************************
 
String _$appRouterHash() => r'stub_run_build_runner_to_regenerate';
 
/// Auto-generated by riverpod_generator — run:
///   dart run build_runner build --delete-conflicting-outputs
@ProviderFor(appRouter)
final appRouterProvider = AutoDisposeProvider<GoRouter>.internal(
  appRouter,
  name: r'appRouterProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$appRouterHash,
  dependencies: null,
  allTransitiveDependencies: null,
);
 
typedef AppRouterRef = AutoDisposeProviderRef<GoRouter>;